version: "3.1"
services:
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"

    postgres:
        image: postgres:11
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "guest"
            POSTGRES_PASSWORD: "guest"
            POSTGRES_DB: "guestdb"
    
    pgadmin:
        image: dpage/pgadmin4:4.26
        restart: always
        ports:
            - "8080:80"
        environment: 
            PGADMIN_DEFAULT_EMAIL: "guest@guest.com"
            PGADMIN_DEFAULT_PASSWORD: "guest"
            PGADMIN_LISTEN_PORT: 80
        links:
            - "postgres:pgsql-server"
